version: '3.8'

services:
  pdf2md-mcp:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: pdf2md-mcp-server
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - uploads-data:/app/uploads
      - output-data:/app/output
      - temp-data:/app/temp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - pdf2md-network

  # Nginx reverse proxy for SSL termination and load balancing
  nginx:
    image: nginx:alpine
    container_name: pdf2md-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - pdf2md-mcp
    restart: unless-stopped
    networks:
      - pdf2md-network

networks:
  pdf2md-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.38.0.0/16

volumes:
  uploads-data:
  output-data:
  temp-data: