version: '3.8'

services:
  pdf2md-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf2md-mcp-server
    ports:
      - "3000:3000"
    environment:
      - MCP_TRANSPORT=http
      - PORT=3000
      - HOST=0.0.0.0
      - PYTHONUTF8=1
      - NODE_ENV=production
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
    volumes:
      # Volume mounts for file processing
      - ./uploads:/app/uploads
      - ./output:/app/output
      - ./temp:/app/temp
      # Optional: Mount for custom configurations
      - ./.env:/app/.env:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.25'
    networks:
      - pdf2md-network

networks:
  pdf2md-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.38.0.0/16