[project]
name = "ocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "markitdown>=0.0.1a3",
    "openai-whisper",
    "torch>=2.4.0",
    "torchaudio>=2.1.0",
    "transformers>=4.36.0",
    "faster-whisper>=1.0.0",
    "datasets",
    "accelerate",
    "nvidia-cublas-cu12",
    "nvidia-cudnn-cu12>=9.0.0",
]
