[project]
name = "ocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "markitdown>=0.0.1a3",
    # Enhanced Audio Transcription (RTX 3060 optimized)
    "openai-whisper>=20231117",
    "torch>=2.1.0",
    "torchaudio>=2.1.0",
    "transformers>=4.36.0",
    "accelerate>=0.24.0",
    # Audio Processing
    "pydub>=0.25.1",
    "ffmpeg-python>=0.2.0",
    # GPU Memory Management
    "nvidia-ml-py>=12.0.0; sys_platform != 'darwin'",
    "psutil>=5.9.0",
    # Audio Format Support
    "librosa>=0.10.0",
    "soundfile>=0.12.1",
    # Better Whisper (faster inference)
    "faster-whisper>=0.10.0",
]
